### ISSUE TITLE
Focus Appearance SC not updated to latest recommenation

### ISSUE THREAD

**Issue by sirrah-tam** [Grunet/digestible-wcag#7]
The most recent email (sent on 11/29/23) was regarding the Focus Appearance (Minimum) success criteria which was listed as 2.4.11 and marked as a AA criteria. The published recommendation now has that as a AAA criteria and numbered as 2.4.13. 

Reference: https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance

**Comment by Grunet** [comment]
Sorry for the super long delay, but this should be fixed now (I just got around to updating everything to the latest released version of WCAG 2.2).

https://htmlpreview.github.io/?https://raw.githubusercontent.com/Grunet/digestible-wcag-sc-emails/master/dist/2-4-13.html should show what the new criterion looks like.

Thanks for reporting it!
